repos:
- repo: local
  hooks:
  - id: format
    name: Format code
    entry: puro dart format .
    language: system
    files: \.(dart)$
  - id: analyze
    name: Analyze code
    entry: puro dart analyze .
    language: system
    files: \.(dart)$