name: m3_expressive_shapes
description: "Implementation of the Material 3 Expressive Shape Tokens as Flutter ShapeBorders"
version: 0.0.1
homepage:
repository: https://github.com/benthillerkus/m3_expressive_shapes

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  androidx_graphics_shapes:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
