name: androidx_graphics_shapes_example
description: "Example for androidx_graphics_shapes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  androidx_graphics_shapes:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
