import 'package:flutter/painting.dart';
import 'm3e_shapes.dart';

const Map<String, ShapeBorder> allShapes = {
  "Circle": Circle(),
  "Square": Square(),
  "Slanted": Slanted(),
  "Arch": Arch(),
  "Semicircle": SemiCircle(),
  "Oval": Oval(),
  "Pill": Pill(),
  "Triangle": Triangle(),
  "Arrow": Arrow(),
  "Fan": Fan(),
  "Diamond": Diamond(),
  "ClamShell": ClamShell(),
  "Pentagon": Pentagon(),
  "Gem": Gem(),
  "Sunny": Sunny(),
  "Very sunny": VerySunny(),
  "4-sided cookie": Cookie4Sided(),
  "6-sided cookie": Cookie6Sided(),
  "7-sided cookie": Cookie7Sided(),
  "9-sided cookie": Cookie9Sided(),
  "12-sided cookie": Cookie12Sided(),
  "4-leaf clover": Clover4Leaf(),
  "8-leaf clover": Clover8Leaf(),
  "Burst": Burst(),
  "Soft burst": SoftBurst(),
  "Boom": Boom(),
  "Soft Boom": SoftBoom(),
  "Flower": Flower(),
  "Puffy": Puffy(),
  "Puffy Diamond": PuffyDiamond(),
  "Ghost-ish": Ghostish(),
  "Pixel circle": PixelCircle(),
  "Pixel triangle": PixelTriangle(),
  "Bun": Bun(),
  "Heart": Heart(),
};
